n=input("Enter the value")
x= input("Insert the value")
a=["icecream","chocolate","balloon"]
a.append(n)
print(a)
a.remove("chocolate")
print(a)
a.sort()
print(a)
a.reverse()
print(a)
a.insert(1, x)
print(a)
print(a.index(n))
a.pop(2)
print(a)