name="b"
age=20
a=20
price=92.7
print(name,age,price)
print(type(name))
print(type(age))
print(type(price))
print(id(name))
print(id(age))
print(id(price))
print(id(a))
cantien="bhuvi"
library="bhuvi"
print(id(cantien))
print(id(library))
age=float(age)
print(type(age))